### POST request to create a new Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Jack Black",
  "email": "jack.black123@example.com",
  "address": "123 Main St. Capital City",
  "dateOfBirth": "1987-10-03",
  "registeredDate": "2024-11-28"
}

###